dry: true

iterative_data: None
iterations: 10

images_by_iterations: 1
curated_threshold: 0.1
duplicate_threshold: 0

model_config: 'fine_tuning/vitmae.yml'
sub_config:

checkpoint: 'rare-eon-453-h50udox1.ckpt'

devices: [ 2, 3 ]