dry: true

random_state: 42
max_epochs: 100
criterion: 'TMWDL-Cosine'

contrast_factor: 15
size: 256
crop_size: 224
exclude_anchor: [ 'Boring' ]

model_id: 'facebook/vit-mae-large'
pretrained_checkpoint: 'rare-eon-453-h50udox1.ckpt'

batch_size: 32
val_check_interval: 1.0

lr: 0.000001

devices: [ 0 ]