path:
  data:
    root: 'data'
    raw:
      root: 'data/raw'
      train: 'data/raw/train'
      test: 'data/raw/test'
    processed:
      root: 'data/processed'
      train: 'data/processed/train'
      test: 'data/processed/test'
  models:
    root: 'models'
  reports:
    root: 'reports'
    figures: 'reports/figures'
  submissions:
    root: 'submissions'

wandb:
  entity: 'association-rosia'
  project: 'reflection-connection'

archi:
  num_workers: 23

data:
  mean: 0.5189
  std: 0.4847