dry: true

random_state: 42
max_epochs: 25
criterion: 'TMWDL-Cosine'

contrast_factor: 15
size: 256
crop_size: 224
exclude_anchor: [ 'Boring' ]

model_id: 'openai/clip-vit-large-patch14'
checkpoint: None

batch_size: 24
val_check_interval: 1.0

lr: 0.000005

devices: [ 0 ]