torchvision:
  dry: false

  random_state: 42
  max_epochs: 1000
  criterion: 'TMWDL-Cosine'

  contrast_factor: 15
  size: 256
  crop_size: 224
  exclude_anchor: [ 'Boring' ]

  model_id: 'ViT_L_16_SEISMIC31K_SGD'
  checkpoint: None
  
  batch_size: 32
  val_check_interval: 1.0

  lr: 0.000005

  devices: [ 0 ]

transformers:
  dry: false

  random_state: 42
  max_epochs: 1000
  criterion: 'TMWDL-Cosine'

  contrast_factor: 15
  size: 256
  crop_size: 224
  exclude_anchor: [ 'Boring' ]

  model_id: 'google/vit-base-patch16-224-in21k'
  checkpoint: 'treasured-cherry-284-16en0cb3.ckpt'

  batch_size: 32
  val_check_interval: 1.0

  lr: 0.001

  devices: [ 0 ]
