dry: false

random_state: 42
max_epochs: 25
criterion: 'TMWDL-Cosine'

contrast_factor: 25
size: 256
crop_size: 224
exclude_anchor: [ 'Boring' ]

model_id: 'openai/clip-vit-large-patch14'

batch_size: 24

lr: 0.000001