path:
  data: 'data'
  models: 'models'
  reports: 'reports'
  submissions: 'submissions'
  logs: 'logs'

wandb:
  entity: 'association-rosia'
  project: 'reflection-connection'

archi:
  num_workers: 23

data:
  mean: 0.5189
  std: 0.4847