dry: false

random_state: 42
max_epochs: 100
criterion: 'TMWDL-Cosine'

contrast_factor: 25
size: 256
crop_size: 224
exclude_anchor: [ 'Boring' ]

model_id: 'facebook/dinov2-base'

batch_size: 24
val_check_interval: 1

lr: 0.00001

devices: [ 0 ]