dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 24
  dataset_path: ImageNet:split=TRAIN:root=/home/external-rosia/rosia/reflection-connection/data/processed/pretrain/:extra=/home/external-rosia/rosia/reflection-connection/data/processed/pretrain/extra/
  centering: sinkhorn_knopp
student:
  arch: vit_large
  patch_size: 14
  drop_path_rate: 0.2
  ffn_layer: swiglufused
  block_chunks: 4
teacher:
  momentum_teacher: 0.994
  teacher_temp: 0.08
optim:
  epochs: 100
  weight_decay_start: 0.01
  weight_decay_end: 0.1
  base_lr: 0.001
  warmup_epochs: 20
  clip_grad: 2.0
  layerwise_decay: 0.95
crops:
  global_crops_scale:
    - 0.4
    - 1.0
  local_crops_number: 10
  local_crops_size: 98
