dry: false

random_state: 42
max_epochs: 100

crop_size: 224

model_id: 'google/vit-base-patch16-224-in21k'
num_patches: 196 # (crop_size // patch_size) ** 2
num_prototypes: 1000
center_momentum: 0.9

batch_size: 32
val_check_interval: 0.1

lr: 0.0001

devices: [ 0 ] # [ 0, 1, 2, 3 ]