dry: false

random_state: 42
max_epochs: 1000
criterion: 'TMWDL-Cosine'

contrast_factor: 15
size: 256
crop_size: 224
exclude_anchor: [ 'Boring' ]

model_id: 'ViT_L_16_SEISMIC31K_SGD'

batch_size: 32

lr: 0.000005