dry: false

random_state: 42
max_epochs: 1000
criterion: 'TMWDL-Cosine'

contrast_factor: 10
size: 256
crop_size: 224
exclude_anchor: [ 'Boring' ]

model_id: 'google/vit-base-patch16-224-in21k'

batch_size: 32
val_check_interval: 1.0

lr: 0.000005

devices: [ 0 ]