dry: true

type: 'fine-tuning' # pretraining

random_state: 42
max_epochs: 100

crop_size: 224

model_id: 'facebook/vit-mae-large'
checkpoint: 'fanciful-bush-370-lmqv1byw.ckpt'

batch_size: 32
val_check_interval: 1.0

lr: 0.000005

devices: [ 0 ] # [ 0, 1, 2, 3 ]